name: Update and Deploy

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v3

      - name: 下载 classisland-hub-web 仓库
        run: git clone https://github.com/ClassIsland/classisland-hub-web.git

      - name: 复制 images 文件夹内容
        run: |
          mkdir -p classisland-hub-web/public/imgs
          cp -r images/* classisland-hub-web/public/imgs/

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: pnpm@9.9.0

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: 安装依赖
        working-directory: classisland-hub-web
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: 构建文档
        working-directory: classisland-hub-web
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run build
          > dist/.nojekyll

      - name: 打包工件
        working-directory: classisland-hub-web
        shell: sh
        if: runner.os == 'Linux'
        run: |
          tar \
            --directory "./dist/" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .
        env:
          INPUT_PATH: ./build

      - name: 上传工件
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1
          if-no-files-found: error

  deploy:
    needs: update
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2